apiVersion: v1
kind: Pod
metadata:
  name: subnet-router
  labels:
    app: tailscale
spec:
  serviceAccountName: tailscale
  containers:
    - name: tailscale
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: "{{ .Values.image.pullPolicy }}"
      env:
        - name: TS_KUBE_SECRET
          value: tailscale
        - name: TS_USERSPACE
          value: "true"
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.nameAuth }}
              key: TS_AUTHKEY
        - name: TS_ROUTES
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.nameRoutes }}
              key: TS_ROUTES
        - name: TS_EXTRA_ARGS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.nameExtraArgs }}
              key: TS_EXTRA_ARGS
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
  nodeSelector:
    kubernetes.io/arch: "{{ .Values.nodeSelectorArchitecture }}"
